stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - docker build -t registry.gitlab.com/my-group/myapp:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/my-group/myapp:$CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - kubectl set image deployment/myapp myapp=registry.gitlab.com/my-group/myapp:$CI_COMMIT_SHA
    - kubectl rollout status deployment/myapp
  only:
    - main
