apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-${VERSION}
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nishantrepo/goapp:${VERSION}
        ports:
        - containerPort: 8080

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-api-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
