apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nishantrepo/goapp:2.0.0
        ports:
        - containerPort: 8080

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-api-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: go-api-vs
spec:
  hosts:
  - "*"
  gateways:
  - go-api-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: myapp.default.svc.cluster.local
        port:
          number: 8080
