name: CI/CD Pipeline

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: medyagh/setup-minikube@master

    - name: Install Istio CLI
      run: |
        curl -L https://istio.io/downloadIstio | sh -
        sudo mv istio-*/bin/istioctl /usr/local/bin/
        istioctl version

    - name: Install Istio in Minikube
      run: |
        istioctl install --set profile=demo -y
        kubectl label namespace default istio-injection=enabled

    - name: Build and push Docker image
      run: |
        docker build -t nishantrepolocal/myapp:2.0.0 .
        minikube image load nishantrepolocal/myapp:2.0.0

    - name: Deploy to Kubernetes
      run: |
        kubectl config set-context minikube
        kubectl apply -f ./deploy.yaml
        kubectl apply -f ./service.yaml

    - name: Wait for deployment to complete
      run: |
        kubectl rollout status deployment/myapp

    - name: Test Service and Get URL
      run: |
        export INGRESS_HOST=$(minikube ip)
        export INGRESS_PORT=$(kubectl get svc istio-ingressgateway -n istio-system -o jsonpath='{.spec.ports[?(@.port==80)].nodePort}')
        export GATEWAY_URL=$INGRESS_HOST:$INGRESS_PORT
        echo "Your service is accessible at: http://$GATEWAY_URL/"
