name: CI/CD Pipeline

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PR label contain "qa-env"
        run: |
          if [[ ! "${{ github.event.pull_request.labels }}" =~ "qa-env" ]]; then
            echo "No 'qa-env' label found. Exiting workflow."
            labels=${{ toJSON(github.event.pull_request.labels) }}
            echo "Labels: $labels"
            for label in $labels; do
              echo "Label: $label"
            done
          fi

      - name: Set Version
        id: set-version
        run: |
          VERSION=qa-$(echo ${{ github.event.pull_request.number }} | sed 's/\//-/g')
          echo "VERSION=$VERSION" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
          echo "$VERSION"
