name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Minikube
        uses: medyagh/setup-minikube@master

      - name: Build and push Docker image
        run: |
          docker build -t nishantrepolocal/myapp:latest .
          minikube image load nishantrepolocal/myapp:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl config set-context minikube
          kubectl apply -f ./deploy.yaml
          kubectl apply -f ./service.yaml
