name : deploy-command
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "The repository from which the slash command was dispatched"
        required: true
      comment-id:
        description: "The comment-id of the slash command"
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Add reaction
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.event.inputs.repository }}
        comment-id: ${{ github.event.inputs.comment-id }}
        reactions: hooray
