name: qa clean
on:
  workflow_dispatch:

jobs:
  qa-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0

      - name: echo text for cleanup
        run: |
          echo "This is qa-clean3"
          cat read.txt
