name: qa deploy
on:
  workflow_dispatch:

jobs:
  qa-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: echo text for qa-deploy
      run: |
        echo "this is qa-deploy2"
        cat read.txt