name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: deploy

      - name: Confirm commit SHA
        run: |
          echo "Pull Request Data: ${{ toJSON(github.event.client_payload.pull_request) }}"
