name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          # Checkout the branch from which the PR originated
          repository: ${{ github.event.issue.pull_request.head.repo.full_name }}
          ref: ${{ github.event.issue.pull_request.head.ref }}

      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: |
            deploy
            test
          dispatch-type: workflow
