on:
  repository_dispatch:
    types: [run-black-command]
jobs:
  runBlack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{github.event.client_payload.pull_request.head.repo.full_name}}
          ref: ${{github.event.client_payload.pull_request.head.ref}}
          token: ${{ secrets.PAT }}
      - name: Slash Command Dispatch
        run: black .
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Run black" -a
          git push