# .github/workflows/update_virtual_service.yml
name: Update VirtualService

on:
  workflow_call:
    inputs:
      commit_hash:
        description: 'The commit hash to insert in the VirtualService file'
        required: true
        type: string

concurrency:
  group: workflow-lock
  cancel-in-progress: false

jobs:
  update_virtual_service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update VirtualService File with Commit Hash
      run: |
        sleep 100
        COMMIT_HASH="${{ inputs.commit_hash }}"
        yq eval 'select(.kind == "VirtualService").spec.http[0].route[0].destination.version =  "'"$COMMIT_HASH"'"' -i virtualService.yaml
        kubectl apply -f ./virtualService.yaml
